image: alpine:latest

stages:
  - deploy

pages:
    stage: deploy
    script:
        - mkdir -p public
        - mv index.html public/
        - "деплой пошол"
    artifacts:
        paths:
            - public
    only:
        - main